### ISSUE TITLE
Release 1.0 Stable Branch!

### ISSUE THREAD

**Issue by ovr** [nkt/doctrine-columns#3]
All your code gets stable public api

Remove

```
"minimum-stability": "dev"
```

**Comment by nkt** [comment]
why?

**Comment by ovr** [comment]
http://habrahabr.ru/post/134033/

> Если ваш продукт начали использовать конечные потребители, он должен иметь версию 1.0.0. Если у вас есть стабильное открытое API, вы должны перейти на 1.0.0. Если вы переживаете об обратной совместимости, вы должны перейти на 1.0.0.
